name: Build APK
on:
  push:

env:
  USERNAME: malvezzidatr
  PASSWORD: c010203684

jobs:
  publish:
    name: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: setup expo and eas
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EAS_BUILD }}
      - name: install dependencies
        run: yarn install
      - name: Jest
        run: yarn test
      - name: login in expo account
        run: expo login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
      - name: build on EAS
        run: eas build -p android --profile development
