name: Build APK

on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Generating build
    runs-on: ubuntu-latest
    steps:
      - name: Jest
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn
      - run: yarn test