name: Build APK

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - user: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Setup Expo and EAS
        user: expo/expo-github-actions@v7
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EAS_BUILD }}
      - name: Install dependencies
        run: yarn install
      - name: Build on EAS
        run: eas build --platform android --profile development